name: Build and Publish

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - name: Publish
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
        npm publish || true
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
